//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinaSys.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinaSys.Web.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El recurso protegido no fue encontrado..
        /// </summary>
        internal static string Auth_ProtectedResourceNotFound {
            get {
                return ResourceManager.GetString("Auth_ProtectedResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu rol no tiene acceso al recurso solicitado..
        /// </summary>
        internal static string Auth_RolesHasNoAccessToProtectedResource {
            get {
                return ResourceManager.GetString("Auth_RolesHasNoAccessToProtectedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tienes acceso al recurso solicitado..
        /// </summary>
        internal static string Auth_UserHasNoAccessToProtectedResource {
            get {
                return ResourceManager.GetString("Auth_UserHasNoAccessToProtectedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo registrar el usuario..
        /// </summary>
        internal static string Auth_UserRegistrationFailed {
            get {
                return ResourceManager.GetString("Auth_UserRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo eliminar la incubadora..
        /// </summary>
        internal static string BusinessIncubator_DeleteFailed {
            get {
                return ResourceManager.GetString("BusinessIncubator_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falló la consulta de incubadoras..
        /// </summary>
        internal static string BusinessIncubator_FilterQueryFailed {
            get {
                return ResourceManager.GetString("BusinessIncubator_FilterQueryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe una incubadora con esa llave..
        /// </summary>
        internal static string BusinessIncubator_KeyAlreadyExists {
            get {
                return ResourceManager.GetString("BusinessIncubator_KeyAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe una incubadora con ese nombre..
        /// </summary>
        internal static string BusinessIncubator_NameAlreadyExists {
            get {
                return ResourceManager.GetString("BusinessIncubator_NameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La incubadora no fue encontrada..
        /// </summary>
        internal static string BusinessIncubator_NotFound {
            get {
                return ResourceManager.GetString("BusinessIncubator_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo restaurar la incubadora..
        /// </summary>
        internal static string BusinessIncubator_RestoreFailed {
            get {
                return ResourceManager.GetString("BusinessIncubator_RestoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo cambiar el estado del proyecto..
        /// </summary>
        internal static string Project_ChangeStatusFailed {
            get {
                return ResourceManager.GetString("Project_ChangeStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo crear el proyecto..
        /// </summary>
        internal static string Project_CreationFailed {
            get {
                return ResourceManager.GetString("Project_CreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo eliminar el proyecto..
        /// </summary>
        internal static string Project_DeleteFailed {
            get {
                return ResourceManager.GetString("Project_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El proyecto no fue encontrado..
        /// </summary>
        internal static string Project_NotFound {
            get {
                return ResourceManager.GetString("Project_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo restaurar el proyecto..
        /// </summary>
        internal static string Project_RestoreFailed {
            get {
                return ResourceManager.GetString("Project_RestoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo actualizar el proyecto..
        /// </summary>
        internal static string Project_UpdateFailed {
            get {
                return ResourceManager.GetString("Project_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo agregar el límite..
        /// </summary>
        internal static string Subscription_BusinessIncubatorAddLimitFailed {
            get {
                return ResourceManager.GetString("Subscription_BusinessIncubatorAddLimitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La incubadora ya tiene un paquete asignado..
        /// </summary>
        internal static string Subscription_BusinessIncubatorAlreadyHasPackage {
            get {
                return ResourceManager.GetString("Subscription_BusinessIncubatorAlreadyHasPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudieron limpiar los límites..
        /// </summary>
        internal static string Subscription_BusinessIncubatorClearLimitsFailed {
            get {
                return ResourceManager.GetString("Subscription_BusinessIncubatorClearLimitsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo asignar el paquete a la incubadora..
        /// </summary>
        internal static string Subscription_BusinessIncubatorPackageCreateFailed {
            get {
                return ResourceManager.GetString("Subscription_BusinessIncubatorPackageCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el paquete asignado a la incubadora..
        /// </summary>
        internal static string Subscription_BusinessIncubatorPackageNotFound {
            get {
                return ResourceManager.GetString("Subscription_BusinessIncubatorPackageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo eliminar el límite..
        /// </summary>
        internal static string Subscription_BusinessIncubatorRemoveLimitFailed {
            get {
                return ResourceManager.GetString("Subscription_BusinessIncubatorRemoveLimitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo cambiar la versión del paquete..
        /// </summary>
        internal static string Subscription_BusinessIncubatorSwitchVersionFailed {
            get {
                return ResourceManager.GetString("Subscription_BusinessIncubatorSwitchVersionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudieron obtener los límites efectivos..
        /// </summary>
        internal static string Subscription_GetEffectiveLimitFailed {
            get {
                return ResourceManager.GetString("Subscription_GetEffectiveLimitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo crear el paquete..
        /// </summary>
        internal static string Subscription_PackageCreationFailed {
            get {
                return ResourceManager.GetString("Subscription_PackageCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró el paquete..
        /// </summary>
        internal static string Subscription_PackageNotFound {
            get {
                return ResourceManager.GetString("Subscription_PackageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo actualizar el paquete..
        /// </summary>
        internal static string Subscription_PackageUpdateFailed {
            get {
                return ResourceManager.GetString("Subscription_PackageUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontró la versión del paquete..
        /// </summary>
        internal static string Subscription_PackageVersionNotFound {
            get {
                return ResourceManager.GetString("Subscription_PackageVersionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo guardar la versión del paquete..
        /// </summary>
        internal static string Subscription_PackageVersionUpsertFailed {
            get {
                return ResourceManager.GetString("Subscription_PackageVersionUpsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error inesperado..
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hay campos inválidos en el formulario..
        /// </summary>
        internal static string Validation_SomeFieldsAreInvalid {
            get {
                return ResourceManager.GetString("Validation_SomeFieldsAreInvalid", resourceCulture);
            }
        }
    }
}
